# Generated by Django 5.0.3 on 2024-03-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_articleseries_options_article_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_slug',
        ),
    ]
