# Generated by Django 5.0.3 on 2024-03-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_article_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(default='default', unique=True, verbose_name='Article slug'),
            preserve_default=False,
        ),
    ]
