# Generated by Django 5.0.3 on 2024-03-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_article_image_alter_articleseries_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='articleseries',
            name='image',
        ),
    ]
