# Generated by Django 5.0.3 on 2024-03-10 17:09

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_article_image_remove_articleseries_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/noimage.jpg', max_length=255, upload_to=myapp.models.Article.image_upload_to),
        ),
        migrations.AddField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='default/noimage.jpg', max_length=255, upload_to=myapp.models.ArticleSeries.image_upload_to),
        ),
    ]
